### PR TITLE
NotoSansArabicUI: remove unused anchors that cause build error

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/googlei18n/fontmake/issues/447

This removes all the extra unused anchors from the following glyphs:
    "twodotsverticalabove-ar.small",
    "twodotshorizontalabove-ar.small",
    "threedotsdownabove-ar.small",
    "fourdotsabove-ar.small",

and only keeps the "_center" anchor, which is the only one that is actually being used to create a few other composite glyphs, namely "dyeh-ar", "dyeh-ar.fina", "nyeh-ar", "nyeh-ar.fina", "tcheh-ar", "tcheh-ar.fina", "tcheheh-ar", "tcheheh.fina".

By removing those extra anchors, we work around an error that occurs while building the mark feature, which is caused by the fact that those glyphs are being treated as mark glyphs by the MarkFeatureWriter (as they contain `_`-prefixed anchors), and they refer to more than one mark class (`_center` and `_top`), and feaLib rightly fails to compile when a mark lookup contain overlapping mark classes.

Besides, these particular glyphs are marked as non-export (they are only used to create composite glyphs), so ideally the feature compiler should exclude them from the generated mark feature.
Currently however in fontmake this subsetting stage that gets rid of non-export glyphs happens only after the full font has been compiled. We are going to change that (requires changes to feaLib to allow to subset the feature file source), but in the mean time this patch at least allows to build the Noto Sans Arabic UI fonts without the error, and without change in functionality.

### CODE REVIEW

**Comment by anthrotype** [comment]
I was able to build locally Noto Sans Arabic UI after applying this patch with these command:

```
$ git pull
$ ./build setup
$ ./build src/NotoSansArabicUI-MM.glyphs
```

@punchcutter could please you take a look and confirm these removed anchors are unnecessary and can be dropped? thanks

**Comment by punchcutter** [comment]
Yes, that's the same thing I did locally and it seems fine. Since only the center anchors are used the others are pointless. It would be nice if Glyphs said something, but that would be easy to script and check.

**Comment by anthrotype** [comment]
Thanks Zachary!

**Comment by punchcutter** [comment]
Actually, not so easy to script because these components could do Automatic Alignment with a different anchor in different composite glyphs. That would be a horrible way to set things up, but the way Glyphs does Automatic Alignment allows for that. For example you could have a dot with _top,  _center, and _bottom anchors and it could be a component in three different glyphs, one with a top anchor, one with a center anchor, and the other with a bottom anchor. That doesn't really make sense, but it's possible and in this particular case there's no way to know for sure without looking.

**Comment by anthrotype** [comment]
I did check and they appear to be used only in the _center, in the composite glyphs I mentioned above.

**Pull request merged**
